title: Xiaohui Luo
description: Ph.D. student in Psychological Statistics and Psychometrics at Beijing Normal University.
author: Xiaohui Luo
email: xiaohui_luo@mail.bnu.edu.cn
baseurl: ""  
url: "https://luoxh3.github.io"
twitter_username: ""
github_username: luoxh3

# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed

# 启用搜索
search_enabled: true

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# 侧边栏设置
just_the_docs:
  heading_anchors: true
  nav_depth: 2

