title: Xiaohui Luo
description: Ph.D. student in Psychological Statistics and Psychometrics at Beijing Normal University.
author: Xiaohui Luo
email: xiaohui_luo@mail.bnu.edu.cn
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://luoxh3.github.io"
twitter_username: #
github_username: luoxh3

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

navigation:
  - text: "Home"
    url: /
  - text: "Publications"
    url: /publications/
  - text: "CV"
    url: /cv/
  - text: "Contact"
    url: /contact/